---
- name: Join worker nodes to Kubernetes cluster
  hosts: kube_node
  become: yes
  tasks:
    - name: Copy join command to worker nodes
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: '0777'

    - name: Join cluster
      command: sh /tmp/kubernetes_join_command
      register: joined
      changed_when: joined.rc == 0