---
- name: Initialize Kubernetes cluster
  hosts: kube_control_plane
  become: yes
  tasks:
    - name: Ensure kubelet is running
      systemd:
        name: kubelet
        state: started
        enabled: yes

    - name: Open firewall port for Kubernetes API server
      ufw:
        rule: allow
        port: 6443
        proto: tcp

    - name: Initialize cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_default_ipv4.address }}
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy admin.conf to user kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0644'
        remote_src: yes

    - name: Wait for API server to be ready
      command: kubectl get nodes --kubeconfig=/home/ubuntu/.kube/config
      register: api_check
      until: api_check is success
      retries: 10
      delay: 10
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      when: kubeadm_init is success

    - name: Install Flannel network
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      register: flannel_install
      until: flannel_install is success
      retries: 5
      delay: 10
      when: kubeadm_init is success