# username: ubuntu
# password: P"ssw0rd

---
- name: Create VMs in vSphere
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: "vcsa-storage.testlab.systex.hk" # ip: 192.168.128.200
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "P@ssw0rd"
    vcenter_datacenter: "SYSTEX"
    vcenter_cluster: "Cluster"
    vm_template: "ubuntu-22.04-template"
    vm_folder: "/Direct Team/Arnold Yeung"
    vm_network: "VM Lab Network (subnet 192.168.128.0/17)"
    vm_datastore: "Lab_DS"
    vm_count: 3 
    vm_base_name: "ay_k8s_node"
    vm_cpu: 2
    vm_memory: 4096  
    vm_disk_size: 100
    vm_ips:
      - "192.168.148.69"  # Master
      - "192.168.148.70"  # Worker 1
      - "192.168.148.71"  # Worker 2
    vm_netmask: "255.255.128.0"
    vm_gateway: "192.168.128.1"
    vm_dns_servers:
      - "192.168.148.54"
  tasks:
    - name: Create ubuntu Vms
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        name: "{{ vm_base_name }}{{ item.0 }}"
        template: "{{ vm_template }}"
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        folder: "{{ vm_folder }}"
        datastore: "{{ vm_datastore }}"
        state: poweredon
        wait_for_ip_address: true
        hardware:
          num_cpus: "{{ vm_cpu }}"
          memory_mb: "{{ vm_memory }}"
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: thin
            datastore: "{{ vm_datastore }}"
        networks:
          - name: "{{ vm_network }}"
            ip: "{{ item.1 }}"
            netmask: "{{ vm_netmask }}"
            gateway: "{{ vm_gateway }}"
            dns_servers: "{{ vm_dns_servers }}"
        customization:
          hostname: "{{ vm_base_name }}{{ item.0 }}"
      loop: "{{ range(0, vm_count) | zip(vm_ips) | list }}"