- name: Create VMs in vSphere
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/vars.yml
  tasks:
    - name: Create ubuntu Vms
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        name: "{{ vm_base_name }}{{ item.0 }}"
        template: "{{ vm_template }}"
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        folder: "{{ vm_folder }}"
        datastore: "{{ vm_datastore }}"
        state: poweredon
        wait_for_ip_address: true
        hardware:
          num_cpus: "{{ vm_cpu }}"
          memory_mb: "{{ vm_memory }}"
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: thin
            datastore: "{{ vm_datastore }}"
        networks:
          - name: "{{ vm_network }}"
            ip: "{{ item.1 }}"
            netmask: "{{ vm_netmask }}"
            gateway: "{{ vm_gateway }}"
            dns_servers: "{{ vm_dns_servers }}"
        customization:
          hostname: "{{ vm_base_name }}{{ item.0 }}"
      loop: "{{ range(0, vm_count) | zip(vm_ips) | list }}"